In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
from sklearn.linear_model import LinearRegression

In [2]:
df = pd.read_excel("GrupC.xlsx")
df

,Bakim_ID,Bakim_Onceligi,Vardiya,Tesis_Bolgesi,Makine_Saglik_Durumu,Makine_Yasi,Calisma_Saati,Titreşim_Seviyesi,Ariza_Sayisi,Duruş_Suresi_Saat,Ortam_Sicakligi,Toplam_Bakim_Maliyeti
0,BKM1001,Dusuk,Gece,Guney,Kusursuz,1.0,1960.0,1.16,3.0,10.4,41.8,15767.85
1,BKM1002,Orta,Gece,Dogu,Kusursuz,7.0,924.0,1.40,1.0,8.1,30.2,14756.24
2,BKM1003,Kritik,Gece,Batı,Yıpranmış,5.0,2113.0,1.69,4.0,9.2,25.7,24976.29
3,BKM1004,Kritik,Gece,Merkez,Zayıf,12.0,2898.0,2.20,0.0,7.4,22.0,25770.41
4,BKM1005,Orta,Hafta Sonu,Dogu,Kritik,10.0,1925.0,1.26,3.0,3.4,28.1,15910.66
...,...,...,...,...,...,...,...,...,...,...,...,...
495,BKM1496,Dusuk,Gunduz,Kuzey,Yıpranmış,1.0,1354.0,2.34,5.0,19.9,43.2,23918.19
496,BKM1497,Orta,Hafta Sonu,Kuzey,Yıpranmış,6.0,1868.0,3.57,4.0,3.6,33.1,24398.57
497,BKM1498,Yuksek,Hafta Sonu,Kuzey,Zayıf,12.0,1797.0,1.55,3.0,9.8,29.2,23983.28
498,BKM1499,Dusuk,Hafta Sonu,Dogu,Kritik,4.0,875.0,0.88,2.0,8.5,38.7,18017.30
499,BKM1500,Kritik,Gunduz,Guney,NaN,8.0,1370.0,1.82,0.0,4.0,42.1,19508.40

In [3]:
df = df.drop("Bakim_ID", axis = 1)
df

,Bakim_Onceligi,Vardiya,Tesis_Bolgesi,Makine_Saglik_Durumu,Makine_Yasi,Calisma_Saati,Titreşim_Seviyesi,Ariza_Sayisi,Duruş_Suresi_Saat,Ortam_Sicakligi,Toplam_Bakim_Maliyeti
0,Dusuk,Gece,Guney,Kusursuz,1.0,1960.0,1.16,3.0,10.4,41.8,15767.85
1,Orta,Gece,Dogu,Kusursuz,7.0,924.0,1.40,1.0,8.1,30.2,14756.24
2,Kritik,Gece,Batı,Yıpranmış,5.0,2113.0,1.69,4.0,9.2,25.7,24976.29
3,Kritik,Gece,Merkez,Zayıf,12.0,2898.0,2.20,0.0,7.4,22.0,25770.41
4,Orta,Hafta Sonu,Dogu,Kritik,10.0,1925.0,1.26,3.0,3.4,28.1,15910.66
...,...,...,...,...,...,...,...,...,...,...,...
495,Dusuk,Gunduz,Kuzey,Yıpranmış,1.0,1354.0,2.34,5.0,19.9,43.2,23918.19
496,Orta,Hafta Sonu,Kuzey,Yıpranmış,6.0,1868.0,3.57,4.0,3.6,33.1,24398.57
497,Yuksek,Hafta Sonu,Kuzey,Zayıf,12.0,1797.0,1.55,3.0,9.8,29.2,23983.28
498,Dusuk,Hafta Sonu,Dogu,Kritik,4.0,875.0,0.88,2.0,8.5,38.7,18017.30
499,Kritik,Gunduz,Guney,NaN,8.0,1370.0,1.82,0.0,4.0,42.1,19508.40

In [4]:
df ["Bakim_Onceligi"].value_counts()

Orta      182
Yuksek    127
Dusuk     114
Kritik     67
?          10
Name: Bakim_Onceligi, dtype: int64

In [5]:
df[df["Bakim_Onceligi"] == "?"]

,Bakim_Onceligi,Vardiya,Tesis_Bolgesi,Makine_Saglik_Durumu,Makine_Yasi,Calisma_Saati,Titreşim_Seviyesi,Ariza_Sayisi,Duruş_Suresi_Saat,Ortam_Sicakligi,Toplam_Bakim_Maliyeti
15,?,Gunduz,Kuzey,Kritik,5.0,2033.0,1.18,1.0,5.6,33.1,11750.69
19,?,Gece,Guney,Yıpranmış,9.0,2490.0,2.14,0.0,2.5,30.7,20129.60
61,?,Gece,Kuzey,Zayıf,5.0,2157.0,1.82,1.0,12.5,39.1,18378.56
275,?,Gunduz,Bati,Yıpranmış,1.0,743.0,1.06,1.0,2.7,37.6,18656.34
318,?,Gece,Guney,Kusursuz,10.0,1853.0,0.69,2.0,6.2,28.8,21634.99
406,?,Hafta Sonu,Merkez,Kritik,NaN,778.0,0.66,2.0,11.8,35.5,20482.86
454,?,Gece,Guney,Kritik,9.0,645.0,1.76,1.0,7.4,24.4,19448.46
478,?,NaN,Merkez,Zayıf,18.0,17497.0,0.54,11.0,5.9,35.8,46775.88
481,?,Gunduz,Merkez,Kusursuz,5.0,792.0,0.87,3.0,10.2,42.8,13364.82
490,?,Gunduz,Merkez,Zayıf,3.0,2565.0,1.47,11.0,1.3,30.2,22286.23

In [6]:
df ["Bakim_Onceligi"] = df["Bakim_Onceligi"].replace("?", pd.NA)
df ["Bakim_Onceligi"].value_counts()

Orta      182
Yuksek    127
Dusuk     114
Kritik     67
Name: Bakim_Onceligi, dtype: int64

In [7]:
df["Vardiya"].value_counts()

Gunduz        274
Gece          155
Hafta Sonu     60
Name: Vardiya, dtype: int64

In [8]:
df["Tesis_Bolgesi"].value_counts()

Merkez    133
Kuzey     100
Guney      97
Dogu       80
Bati       70
Batı        7
Name: Tesis_Bolgesi, dtype: int64

In [9]:
df ["Tesis_Bolgesi"] = df["Tesis_Bolgesi"].replace("Batı", "Bati")
df ["Tesis_Bolgesi"].value_counts()

Merkez    133
Kuzey     100
Guney      97
Dogu       80
Bati       77
Name: Tesis_Bolgesi, dtype: int64

In [10]:
df["Makine_Saglik_Durumu"].value_counts()

Kritik       137
Zayıf        134
Yıpranmış     90
Kusursuz      61
İyi           42
Name: Makine_Saglik_Durumu, dtype: int64

In [11]:
df.isnull().sum() #sutün kategorik ise mod | #sayısal değerler ise medyan ve mod

Bakim_Onceligi           10
Vardiya                  11
Tesis_Bolgesi            13
Makine_Saglik_Durumu     36
Makine_Yasi              14
Calisma_Saati            18
Titreşim_Seviyesi        16
Ariza_Sayisi             15
Duruş_Suresi_Saat        14
Ortam_Sicakligi          14
Toplam_Bakim_Maliyeti     0
dtype: int64

In [12]:
x = df.groupby(["Tesis_Bolgesi", "Makine_Saglik_Durumu"])["Bakim_Onceligi"].transform(
    lambda x: x.mode()[0]

)
df["Bakim_Onceligi"] = df["Bakim_Onceligi"].fillna(x)
df["Bakim_Onceligi"].isnull().sum()

0

In [13]:
x = df.groupby(["Tesis_Bolgesi", "Makine_Saglik_Durumu"])["Vardiya"].transform(
    lambda x: x.mode()[0]

)
df["Vardiya"] = df["Vardiya"].fillna(x)
df["Vardiya"].isnull().sum()

1

In [14]:
x = df.groupby(["Vardiya", "Makine_Saglik_Durumu"])["Tesis_Bolgesi"].transform(
    lambda x: x.mode()[0]

)
df["Tesis_Bolgesi"] = df["Tesis_Bolgesi"].fillna(x)
df["Tesis_Bolgesi"].isnull().sum()

1

In [15]:
x = df.groupby(["Vardiya"])["Tesis_Bolgesi"].transform(
    lambda x: x.mode()[0]

)
df["Tesis_Bolgesi"] = df["Tesis_Bolgesi"].fillna(x)
df["Tesis_Bolgesi"].isnull().sum()

0

In [16]:
x = df.groupby(["Vardiya", "Tesis_Bolgesi"])["Makine_Saglik_Durumu"].transform(
    lambda x: x.mode()[0]

)
df["Makine_Saglik_Durumu"] = df["Makine_Saglik_Durumu"].fillna(x)
df["Makine_Saglik_Durumu"].isnull().sum()

1

In [17]:
x = df.groupby(["Vardiya", "Tesis_Bolgesi"])["Makine_Yasi"].transform("median")
df["Makine_Yasi"] = df["Makine_Yasi"].fillna(x)
df["Makine_Yasi"].isnull().sum()

0

In [18]:
x = df.groupby(["Vardiya", "Tesis_Bolgesi"])["Calisma_Saati"].transform("median")
df["Calisma_Saati"] = df["Calisma_Saati"].fillna(x)
df["Calisma_Saati"].isnull().sum()

0

In [19]:
x = df.groupby(["Vardiya", "Tesis_Bolgesi"])["Titreşim_Seviyesi"].transform("mean")
df["Titreşim_Seviyesi"] = df["Titreşim_Seviyesi"].fillna(x)
df["Titreşim_Seviyesi"].isnull().sum()

0

In [20]:
x = df.groupby(["Vardiya", "Tesis_Bolgesi"])["Ariza_Sayisi"].transform("median")
df["Ariza_Sayisi"] = df["Ariza_Sayisi"].fillna(x)
df["Ariza_Sayisi"].isnull().sum()

0

In [21]:
x = df.groupby(["Vardiya", "Tesis_Bolgesi"])["Duruş_Suresi_Saat"].transform("median")
df["Duruş_Suresi_Saat"] = df["Ariza_Sayisi"].fillna(x)
df["Duruş_Suresi_Saat"].isnull().sum()

0

In [22]:
x = df.groupby(["Vardiya", "Tesis_Bolgesi"])["Ortam_Sicakligi"].transform("median")
df["Ortam_Sicakligi"] = df["Ortam_Sicakligi"].fillna(x)
df["Ortam_Sicakligi"].isnull().sum()

0

In [23]:
df.isnull().sum()

Bakim_Onceligi           0
Vardiya                  1
Tesis_Bolgesi            0
Makine_Saglik_Durumu     1
Makine_Yasi              0
Calisma_Saati            0
Titreşim_Seviyesi        0
Ariza_Sayisi             0
Duruş_Suresi_Saat        0
Ortam_Sicakligi          0
Toplam_Bakim_Maliyeti    0
dtype: int64

In [24]:
df

,Bakim_Onceligi,Vardiya,Tesis_Bolgesi,Makine_Saglik_Durumu,Makine_Yasi,Calisma_Saati,Titreşim_Seviyesi,Ariza_Sayisi,Duruş_Suresi_Saat,Ortam_Sicakligi,Toplam_Bakim_Maliyeti
0,Dusuk,Gece,Guney,Kusursuz,1.0,1960.0,1.16,3.0,3.0,41.8,15767.85
1,Orta,Gece,Dogu,Kusursuz,7.0,924.0,1.40,1.0,1.0,30.2,14756.24
2,Kritik,Gece,Bati,Yıpranmış,5.0,2113.0,1.69,4.0,4.0,25.7,24976.29
3,Kritik,Gece,Merkez,Zayıf,12.0,2898.0,2.20,0.0,0.0,22.0,25770.41
4,Orta,Hafta Sonu,Dogu,Kritik,10.0,1925.0,1.26,3.0,3.0,28.1,15910.66
...,...,...,...,...,...,...,...,...,...,...,...
495,Dusuk,Gunduz,Kuzey,Yıpranmış,1.0,1354.0,2.34,5.0,5.0,43.2,23918.19
496,Orta,Hafta Sonu,Kuzey,Yıpranmış,6.0,1868.0,3.57,4.0,4.0,33.1,24398.57
497,Yuksek,Hafta Sonu,Kuzey,Zayıf,12.0,1797.0,1.55,3.0,3.0,29.2,23983.28
498,Dusuk,Hafta Sonu,Dogu,Kritik,4.0,875.0,0.88,2.0,2.0,38.7,18017.30
499,Kritik,Gunduz,Guney,Zayıf,8.0,1370.0,1.82,0.0,0.0,42.1,19508.40

In [25]:
df= pd.get_dummies(df, columns=["Vardiya","Tesis_Bolgesi"], drop_first=True, dtype=int)
df

,Bakim_Onceligi,Makine_Saglik_Durumu,Makine_Yasi,Calisma_Saati,Titreşim_Seviyesi,Ariza_Sayisi,Duruş_Suresi_Saat,Ortam_Sicakligi,Toplam_Bakim_Maliyeti,Vardiya_Gunduz,Vardiya_Hafta Sonu,Tesis_Bolgesi_Dogu,Tesis_Bolgesi_Guney,Tesis_Bolgesi_Kuzey,Tesis_Bolgesi_Merkez
0,Dusuk,Kusursuz,1.0,1960.0,1.16,3.0,3.0,41.8,15767.85,0,0,0,1,0,0
1,Orta,Kusursuz,7.0,924.0,1.40,1.0,1.0,30.2,14756.24,0,0,1,0,0,0
2,Kritik,Yıpranmış,5.0,2113.0,1.69,4.0,4.0,25.7,24976.29,0,0,0,0,0,0
3,Kritik,Zayıf,12.0,2898.0,2.20,0.0,0.0,22.0,25770.41,0,0,0,0,0,1
4,Orta,Kritik,10.0,1925.0,1.26,3.0,3.0,28.1,15910.66,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,Dusuk,Yıpranmış,1.0,1354.0,2.34,5.0,5.0,43.2,23918.19,1,0,0,0,1,0
496,Orta,Yıpranmış,6.0,1868.0,3.57,4.0,4.0,33.1,24398.57,0,1,0,0,1,0
497,Yuksek,Zayıf,12.0,1797.0,1.55,3.0,3.0,29.2,23983.28,0,1,0,0,1,0
498,Dusuk,Kritik,4.0,875.0,0.88,2.0,2.0,38.7,18017.30,0,1,1,0,0,0
499,Kritik,Zayıf,8.0,1370.0,1.82,0.0,0.0,42.1,19508.40,1,0,0,1,0,0

In [26]:
df ["Bakim_Onceligi"].value_counts()

Orta      189
Yuksek    128
Dusuk     116
Kritik     67
Name: Bakim_Onceligi, dtype: int64

In [27]:
df["Bakim_Onceligi"] = df ["Bakim_Onceligi"].map({
    "Kritik": 0,
    "Dusuk": 1,
    "Orta": 2,
    "Yuksek":3
})

df["Makine_Saglik_Durumu"] = df ["Makine_Saglik_Durumu"].map({
    "Kritik": 0,
    "Yıpranmış": 1,
    "Zayıf": 2,
    "İyi": 3,
    "Kusursuz":4
})

In [28]:
df

,Bakim_Onceligi,Makine_Saglik_Durumu,Makine_Yasi,Calisma_Saati,Titreşim_Seviyesi,Ariza_Sayisi,Duruş_Suresi_Saat,Ortam_Sicakligi,Toplam_Bakim_Maliyeti,Vardiya_Gunduz,Vardiya_Hafta Sonu,Tesis_Bolgesi_Dogu,Tesis_Bolgesi_Guney,Tesis_Bolgesi_Kuzey,Tesis_Bolgesi_Merkez
0,1,4.0,1.0,1960.0,1.16,3.0,3.0,41.8,15767.85,0,0,0,1,0,0
1,2,4.0,7.0,924.0,1.40,1.0,1.0,30.2,14756.24,0,0,1,0,0,0
2,0,1.0,5.0,2113.0,1.69,4.0,4.0,25.7,24976.29,0,0,0,0,0,0
3,0,2.0,12.0,2898.0,2.20,0.0,0.0,22.0,25770.41,0,0,0,0,0,1
4,2,0.0,10.0,1925.0,1.26,3.0,3.0,28.1,15910.66,0,1,1,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
495,1,1.0,1.0,1354.0,2.34,5.0,5.0,43.2,23918.19,1,0,0,0,1,0
496,2,1.0,6.0,1868.0,3.57,4.0,4.0,33.1,24398.57,0,1,0,0,1,0
497,3,2.0,12.0,1797.0,1.55,3.0,3.0,29.2,23983.28,0,1,0,0,1,0
498,1,0.0,4.0,875.0,0.88,2.0,2.0,38.7,18017.30,0,1,1,0,0,0
499,0,2.0,8.0,1370.0,1.82,0.0,0.0,42.1,19508.40,1,0,0,1,0,0

In [38]:
df = df.dropna()

In [39]:
X = df.drop("Toplam_Bakim_Maliyeti", axis = 1)
Y = df["Toplam_Bakim_Maliyeti"]

In [48]:
x_train, x_test, y_train, y_test = train_test_split(X, Y,
                                                    test_size=0.2,
                                                    random_state=42) #Verinin bölünme işlemini gerçekleştiriyorum
skaler = StandardScaler()
sutunlar = ["Bakim_Onceligi", "Makine_Saglik_Durumu", "Makine_Yasi", "Calisma_Saati",
           "Titreşim_Seviyesi", "Ariza_Sayisi", "Duruş_Suresi_Saat", "Ortam_Sicakligi"]

x_train[sutunlar] = skaler.fit_transform(x_train[sutunlar])
x_test[sutunlar] = skaler.transform(x_test[sutunlar])

In [41]:
model = LinearRegression()
model.fit(x_train, y_train)

LinearRegression()

In [45]:
y_pred = model.predict(x_test)

In [46]:
mse = mean_squared_error(y_pred, y_test)
r2 = r2_score(y_pred, y_test)
mse, r2

(23308350.180916492, 0.18293224041338407)